std_msgs/Header header                    # 消息头：包含时间戳

interfaces/MotorCommand fl_hip            # 左前髋关节电机命令
interfaces/MotorCommand fl_thigh          # 左前大腿关节电机命令
interfaces/MotorCommand fl_calf           # 左前小腿关节电机命令

interfaces/MotorCommand fr_hip            # 右前髋关节电机命令
interfaces/MotorCommand fr_thigh          # 右前大腿关节电机命令
interfaces/MotorCommand fr_calf           # 右前小腿关节电机命令

interfaces/MotorCommand rl_hip            # 左后髋关节电机命令
interfaces/MotorCommand rl_thigh          # 左后大腿关节电机命令
interfaces/MotorCommand rl_calf           # 左后小腿关节电机命令

interfaces/MotorCommand rr_hip            # 右后髋关节电机命令
interfaces/MotorCommand rr_thigh          # 右后大腿关节电机命令
interfaces/MotorCommand rr_calf           # 右后小腿关节电机命令